apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-ui-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-ui-app
  template:
    metadata:
      labels:
        app: java-ui-app
    spec:
      containers:
        - name: java-ui-app
          image: docker.io/ash271182/java-ui-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-ui-app-service
spec:
  selector:
    app: java-ui-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
